services:
  strfry:
    build: .
    container_name: bikel-relay
    restart: always
    volumes:
      - ./strfry-db:/app/strfry-db
      - ./strfry.conf:/etc/strfry.conf
      - ./filter.js:/app/filter.js
    ports:
      - "127.0.0.1:7777:7777"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    command: ["--config", "/etc/strfry.conf", "relay"]

  caddy:
    image: caddy:2-alpine
    container_name: bikel-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - strfry

volumes:
  caddy_data:
  caddy_config:
