db = "/app/strfry-db"
nofile = 1000000

relay {
    bind = "0.0.0.0"
    port = 7777

    info {
        name = "Bikel Dedicated Relay"
        description = "A private, high-performance Nostr relay for open cycling data."
        contact = "mnpezz@bikel.ink"
    }
}

writePolicy {
    plugin = "/app/filter.js"
}
