db = "/app/strfry-db"
nofile = 1000000

relay {
    bind = "0.0.0.0"
    port = 7777

    info {
        name = "Bikel Dedicated Relay"
        description = "A private, high-performance Nostr relay for open cycling data. Support for decentralized Bikel bot discovery."
        contact = "mnpezz@bikel.ink"
        pubkey = "cc130b7120d00ded76d065bf0bd27e3a36a38d5268208078a1e99aa29ac44adf"
    }
}

writePolicy {
    plugin = "/app/filter.js"
}
